package com.miage.parcauto.util;

/**
 * Enumération des permissions possibles dans l'application.
 * Cette classe définit toutes les actions qui peuvent être autorisées ou refusées
 * en fonction du profil utilisateur.
 *
 * @author MIAGE Holding
 * @version 1.0
 */
public enum Permission {
    // Authentification
    CONNEXION_SYSTEME,
    CHANGEMENT_MDP_PERSONNEL,
    REINIT_MDP_UTILISATEURS,
    
    // Gestion des véhicules
    CONSULTER_VEHICULES_TOUS,
    CONSULTER_VEHICULES_PERSONNEL,
    CONSULTER_VEHICULES_LECTURE,
    AJOUTER_VEHICULE,
    MODIFIER_VEHICULE,
    SUPPRIMER_VEHICULE,
    CHANGER_ETAT_VEHICULE_TOUS,
    CHANGER_ETAT_VEHICULE_LIMITE,
    DECLARER_PANNE_TOUS,
    DECLARER_PANNE_PERSONNEL,
    
    // Affectation des véhicules
    AFFECTER_VEHICULE_RESPONSABLE,
    AFFECTER_VEHICULE_MISSION,
    SUIVI_AFFECTATIONS_TOUS,
    SUIVI_AFFECTATIONS_LECTURE,
    SUIVI_AFFECTATIONS_PERSONNEL,
    
    // Missions
    CREER_MISSION,
    PLANIFIER_MISSION,
    DEMARRER_MISSION,
    CLOTURER_MISSION,
    ANNULER_MISSION,
    ANNULER_MISSION_JUSTIFICATION,
    SAISIR_DEPENSES_MISSION,
    VALIDER_DEPENSES_MISSION,
    
    // Entretien et maintenance
    PLANIFIER_ENTRETIEN_PREVENTIF,
    SUIVI_ENTRETIEN_TOUS,
    SUIVI_ENTRETIEN_PERSONNEL,
    SAISIR_INTERVENTION,
    CLOTURER_INTERVENTION,
    GERER_PRESTATAIRES,
    
    // Assurances et visites techniques
    SOUSCRIRE_ASSURANCE,
    PLANIFIER_VISITE_TECHNIQUE,
    ENREGISTRER_RESULTAT_VISITE,
    ALERTES_ECHEANCES_TOUS,
    ALERTES_ECHEANCES_PERSONNEL,
    
    // Gestion financière
    CREER_COMPTE_SOCIETAIRE,
    CONSULTER_COMPTES_TOUS,
    CONSULTER_COMPTES_PERSONNEL,
    DEPOT_VALIDATION,
    DEPOT_DEMANDE,
    RETRAIT_VALIDATION,
    RETRAIT_DEMANDE,
    GERER_MENSUALITES,
    CONSULTER_MENSUALITES,
    CALCULER_AMORTISSEMENT,
    
    // Gestion documentaire
    UPLOAD_DOCUMENTS_TOUS,
    UPLOAD_DOCUMENTS_TECHNIQUE,
    UPLOAD_DOCUMENTS_PERSONNEL,
    CONSULTER_DOCUMENTS_TOUS,
    CONSULTER_DOCUMENTS_TECHNIQUE,
    CONSULTER_DOCUMENTS_PERSONNEL,
    VALIDER_DOCUMENTS,
    SUPPRIMER_DOCUMENTS,
    
    // Reporting et statistiques
    TABLEAU_BORD_COMPLET,
    TABLEAU_BORD_OPERATIONNEL,
    TABLEAU_BORD_PERSONNEL,
    TABLEAU_BORD_TECHNIQUE,
    INVENTAIRE_PARC,
    STATISTIQUES_UTILISATION,
    STATISTIQUES_UTILISATION_LIMITE,
    ANALYSE_COUTS,
    ETATS_FINANCIERS,
    ETATS_FINANCIERS_PERSONNEL,
    RAPPORTS_PERSONNALISES,
    EXPORT_DONNEES,
    EXPORT_DONNEES_LIMITE,
    EXPORT_DONNEES_PERSONNEL,
    EXPORT_DONNEES_SYSTEM,
    
    // Administration système
    CREER_UTILISATEURS,
    GERER_DROITS_ACCES,
    PARAMETRAGE_FONCTIONNEL,
    PARAMETRAGE_TECHNIQUE,
    SAUVEGARDE_RESTAURATION,
    LOGS_AUDIT_LECTURE,
    LOGS_AUDIT_COMPLET,
    MAINTENANCE_BDD,
    
    // Alertes et notifications
    CONFIGURER_ALERTES,
    ALERTES_SYSTEME,
    ALERTES_OPERATIONNEL,
    ALERTES_PERSONNEL,
    NOTIFICATIONS_ECHEANCES,
    
    // Kilométrage et carburant
    SAISIR_KILOMETRAGE,
    SAISIR_KILOMETRAGE_PERSONNEL,
    SUIVI_CARBURANT,
    SUIVI_CARBURANT_PERSONNEL,
    ANALYSER_PERFORMANCE;
}